### ISSUE TITLE
Цели проекта? зачем этот инструмент? что получим на выходе?

### ISSUE THREAD

**Issue by artbear** [sikuda/php1c.ru#1]
Хотел бы уточнить по целям и назначению инструмента.

Расскажешь?

**Comment by sikuda** [comment]
Цель: Сделать приемлемым качество выполнение кода 1С в php окружении.
Ближайшее назначение: Возможность переноса некоторых удобных наработок 1С для работы внутри корп-портала. 

Пока к сожалению слишком много академического, но будем продираться потихоньку.
